name: Update Subtrees

on:
  repository_dispatch:
    types: [update-subtrees]

jobs:
  update-subtrees:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_FINED_GRAINED_AUTOMATION }}
          fetch-depth: 0  # Necessary for subtree operations

      - name: Update geo-api-php Subtree
        run: |
          git subtree pull --prefix=api/geo https://github.com/shubkb07/geo-api-php.git main --squash

      - name: Update quick-share-web Subtree
        run: |
          git subtree pull --prefix=share https://github.com/shubkb07/quick-share-web.git main --squash

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated subtree update" || echo "No changes to commit"
          git push origin main
