name: Update Submodules and Create Fully-Resolved Branch

on:
  push:
    branches:
      - master  # Trigger on the master branch
  repository_dispatch:
    types: [update_submodules]  # Triggered by webhook

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout master branch with authentication for private submodules
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_PRIVATE_APP_SHUBKB_COM }}  # Use PAT for authentication
          submodules: recursive      # Fetch submodules

      # Step 2: Update submodules in the master branch
      - name: Update Submodules
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Update submodules to the latest state" || echo "No changes to commit"

      # Step 3: Create/Update the master-app branch
      - name: Create/Update master-app Branch
        run: |
          # Ensure we have the latest state of the master-app branch
          git fetch origin master-app || echo "Branch master-app does not exist"
          git checkout -B master-app  # Create or switch to master-app
          
          # Resolve all submodules into the master-app branch
          git submodule foreach --recursive git checkout master || true
          git submodule foreach --recursive git pull origin master || true
          
          # Commit all resolved files into master-app
          git add --all
          git commit -m "Update master-app branch with resolved submodules" || echo "No changes to commit"

          # Push master-app branch
          git push origin master-app --force

      # Step 4: Verify Branch State (Optional)
      - name: Verify Branch
        run: |
          git checkout master-app
          ls -la  # List all files, including resolved submodules
